services:
  - type: web
    name: medcare-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: HOSPITAL_SECRET_PREFIX
        value: "@MedCare"
      - key: FRONTEND_URL
        fromService:
          type: web
          name: medcare-frontend
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: medcare-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: medcare-backend
          envVarKey: RENDER_EXTERNAL_URL
